Feat : 그룹 선택 구현
anniversaryArchive/archive-web pull request #7
Opened 2022-07-08 15:11 UTC by kimsojung318

## 🛠 주요 변경 사항 
1. `App.tsx` 파일에 `Route` 추가
2. `SelectGroup.tsx` 그룹 목록 노출
3. `SearchCafe.tsx` 선택한 그룹 정보 전달
- 일단 `_id` / `name` 정보만 노출하고 있습니다.

<br/>

## 👩‍💻 Code Review 
Reviewer가 Code Review 시 중점적으로 봐야할 부분을 작성해주세요.
1. `SelectGroup.tsx`
- `TypeScript` Type 지정 방법
- `Map` 사용 방법

<br/>

## 📸 스크린샷
- 그룹 목록 화면
![220708_그룹 선택](https://user-images.githubusercontent.com/68046496/178018404-ab3499d4-2b86-4a7d-922c-6287d1d6a8e1.png)
- 그룹 선택 후 화면
![220708_그룹 선택 후 페이지 이동](https://user-images.githubusercontent.com/68046496/178018424-14e5c374-c74d-4e73-b41c-ef26d68baea8.png)

<br/>

## ✅ Test Checklist 

- [ ] 그룹 로고가 잘 나오는지
- [ ] 그룹 클릭 시 `_id` / `name` 정보가 노출되는지

<br/>

## 🙏 To Reviewers 
그룹 로고는 임시로 추가했습니다!
React + TS 지식이 별로 없어서 구글링하면서 많은 코드들 참고 했습니다. 이상한 부분 언제든지 코멘트 주세요!

2022-07-08 15:48 UTC, chochozabe commented on src/App.tsx
> +import SearchCafe from "./components/pages/SearchCafe";
component 폴더 안에 pages 라는 폴더를 따로 판 이유가 있나용??

2022-07-08 15:49 UTC, chochozabe commented on src/components/pages/SearchCafe.tsx
> +  console.log(state);
개발에 사용한 console.log 는 커밋 시에 삭제부탁드립니다~!

2022-07-08 15:55 UTC, kimsojung318 commented on src/components/pages/SearchCafe.tsx
> +  console.log(state);
네~!

2022-07-08 15:57 UTC, chochozabe commented on src/components/pages/SearchCafe.tsx
> +  const name = state.name;
`{ id: string; name: string }` 을 따로 type으로 지정하면 좋을 것 같습니다~
추가적으로 id, name 을 따로 정의하지 않고 `const {id, name} = location.state as { id: string; name: string };` 같이 객체 디스트럭처링 표현식을 통해 가져오면 간결하게 작성할 수 있습니다 😝

2022-07-08 15:57 UTC, kimsojung318 commented on src/App.tsx
> +import SearchCafe from "./components/pages/SearchCafe";
자주 사용하는 컴포넌트가 아닌 페이지로 인식해서 폴더를 따로 생성했습니다!

2022-07-08 15:59 UTC, chochozabe commented on src/components/pages/SelectGroup.tsx
> +const GROUP_USER = gql`
이런 쿼리문은 여러 곳에서 재사용할 수 있으니 폴더를 하나 만들어서 관리하면 좋을것 같아요👍

2022-07-08 16:01 UTC, chochozabe commented on src/components/pages/SelectGroup.tsx
> +export type Logo = {
타입은 일반적으로 src 폴더 아래 types 폴더를 만들어서 관리합니다! 타입이 생각보다 여러군데 재사용이 많이 되더라구요🤧

2022-07-08 16:03 UTC, chochozabe commented on src/components/pages/SelectGroup.tsx
> +function selectGroupList () {
이런 함수는 따로 component로 빼면 좋을것 같습니다!

2022-07-08 16:05 UTC, bongguma approved these changes
여경님 코멘트 아래 궁금한 점 하나 달아두었습니다! 기능 구현 수고하셨습니다 :)

2022-07-08 16:13 UTC, kimsojung318 commented on src/components/pages/SelectGroup.tsx
> +const GROUP_USER = gql`
apollo/gql 폴더 생성해서 따로 빼두었습니다!

2022-07-08 16:17 UTC, chochozabe commented on src/components/pages/SelectGroup.tsx
> +        <Link to="/searchCafe" state={{ id: `${group._id}`, name: `${group.name}` }}>
코드에는 아무런 영향은 없지만 템플릿 리터럴을 사용하지 않고 아래처럼 사용해도 될 것 같습니다!👀
 `<Link to="/searchCafe" state={{ id: group._id, name: group.name }}>`

2022-07-08 16:19 UTC, chochozabe commented on src/components/pages/SelectGroup.tsx
> +            src={`${imgURL}` + `${group.logo._id}`}
템플릿 리터럴을 사용했기때문에 따로 + 로 연결하지 않고 ``src={`${imgURL} ${group.logo._id}`}`` 로 사용하는 것이 더 좋아보입니다!! 👀

2022-07-08 16:27 UTC, kimsojung318 commented on src/components/pages/SelectGroup.tsx
> +        <Link to="/searchCafe" state={{ id: `${group._id}`, name: `${group.name}` }}>
수정했습니다!

2022-07-08 16:29 UTC, kimsojung318 commented on src/components/pages/SelectGroup.tsx
> +            src={`${imgURL}` + `${group.logo._id}`}
수정했습니다!

2022-07-08 16:29 UTC, kimsojung318 commented on src/components/pages/SelectGroup.tsx
> +    <CardContent sx={{ flexGrow: 1, padding: '3% 0 0 5%' }}>
따로 없습니다!

2022-07-08 16:30 UTC, chochozabe requested changes
수고하셨습니다아~~ 👏👏
코멘트 몇 개 남겨두었습니다! 보시고 수정할 부분 수정해서 커밋 부탁드립니다!

2022-07-08 17:11 UTC, kimsojung318 commented on src/components/pages/SelectGroup.tsx
> +function selectGroupList () {
수정했습니다!

2022-07-08 17:11 UTC, kimsojung318 commented on src/components/pages/SelectGroup.tsx
> +export type Logo = {
수정했습니다!

2022-07-08 17:12 UTC, kimsojung318 commented on src/components/pages/SelectGroup.tsx
> +    <Grid container spacing={1} sx={{ padding: '2% 5%' }}>
제가 아직 emotion/styled 지식이 명확하지 않아서 일단 install만 하고 사용하지는 않았습니다. 추후 개발 시 적용해 보도록 하겠습니다!

2022-07-09 00:11 UTC, kimsojung318 commented on src/App.tsx
> +import SearchCafe from "./components/pages/SearchCafe";
수정했습니다!

2022-07-11 01:03 UTC, bongguma commented on src/components/pages/SearchCafe.tsx
> +  const name = state.name;
아!!! 위와 같은 표현식을 디스트럭처링 표현식으로 표현하는군요!?! 보내주신 링크까지 한번 확인해보겠습니다!

2022-07-11 01:31 UTC, chochozabe requested changes
수정된 부분 확인 후 코멘트 남겨두었습니다!
제가 코드를 실행해보니 이미지 로딩이 조금 느린것같은데 확인 후 조치 부탁드립니다! 지연로딩이나 suspense를 이용하면 될 것같 은데 더 좋은 의견이 있으시다면 그 방법으로 사용하셔도 무방합니다👐👐

2022-07-11 01:31 UTC, chochozabe commented on src/components/selectGroupList.tsx
> +    const nameList: JSX.Element[] = data.groups.map((group:Groups, index:number) =>
map 안에 내용을 컴포넌트로 빼고 return에서 map을 불러서 사용하면 더욱 깔끔한 코드가 될것같습니다!
그리고 `index`를 key 값으로 사용하는 것은 react 공식문서에서 권장하지 않는 방법입니다! group의 `_id`를 key 값으로 사용하는 건 어떨까요?
[참고](https://medium.com/sjk5766/react-%EB%B0%B0%EC%97%B4%EC%9D%98-index%EB%A5%BC-key%EB%A1%9C-%EC%93%B0%EB%A9%B4-%EC%95%88%EB%90%98%EB%8A%94-%EC%9D%B4%EC%9C%A0-3ce48b3a18fb)

2022-07-11 01:31 UTC, chochozabe commented on src/types/groupList.ts
> +type Groups = {
groups 보단 group이라는 명칭이 어떨까요?! 객체보단 groups는 배열에 더 맞는 네이밍같습니다!!

2022-07-11 02:47 UTC, kimsojung318 commented on src/types/groupList.ts
> +type Groups = {
수정했습니다!

2022-07-11 02:51 UTC, kimsojung318 commented on src/components/selectGroupList.tsx
> +import styled from '@emotion/styled'
수정했습니다!

2022-07-11 02:53 UTC, kimsojung318 commented on src/components/selectGroupList.tsx
> +import { Groups } from "../types/groupList"
보통 어떤 순서로 넣어요??

2022-07-11 02:59 UTC, chochozabe commented on src/components/selectGroupList.tsx
> +import { Groups } from "../types/groupList"
권고하는 모듈 임포트 순서는 [ 표준 라이브러리 모듈 → 직접 만든 모듈 ] 입니다!

2022-07-11 03:00 UTC, kimsojung318 commented on src/components/selectGroupList.tsx
> +import { Groups } from "../types/groupList"
수정했습니다!

2022-07-11 03:57 UTC, kimsojung318 commented on src/components/selectGroupList.tsx
> +    const nameList: JSX.Element[] = data.groups.map((group:Groups, index:number) =>
index 삭제하고 useQuery에서 가져온 loading 데이터 사용하여 로딩페이지 따로 생성하였습니다! 그리고 Map 컴포넌트 분리를 어떻게 해야할지 몰라서 기존 코드에서 if 사용으로 생기는 return 코드 중복 제거했습니다!

2022-07-11 04:51 UTC, hyejin-1010 reviewed
수고하셨습니다🙇‍♀️ 몇 개 코멘트를 달아봤습니다!! 거의 다 그냥 개인적인 제안 혹은 의견 정도이기 때문에 읽고 반영하지 않으셔도 괜찮습니다 !!

2022-07-11 04:51 UTC, hyejin-1010 commented on src/components/groupMap.tsx
> +class groupMap extends Component {
현재 이 component는 어디서도 사용되지 않는 거 같은데, 무슨 용도의 component 일까요??

2022-07-11 04:51 UTC, hyejin-1010 commented on src/components/selectGroupList.tsx
> +  const nameList: JSX.Element[] = data.groups.map((group:Group) =>
이거는 그냥 naming 관련한 의견인데 `nameList`보다는 `groupList`라던지  `groupBoxes` ,,? 같은 이름이 더 직관적이지 않을까 싶어요! 🤔 nameList라기에는 name이 안 들어가 있는 거 같아서요!

2022-07-11 04:51 UTC, hyejin-1010 commented on src/components/selectGroupList.tsx
> +  const imgURL = "https://anniversary-archive.herokuapp.com/image/";
`https://anniversary-archive.herokuapp.com` 을 config로 따로 빼서 사용하는 게 좋지 않을까요?? 🤔 apollo 쪽 세팅부분이랑 이 부분에 String으로 들어가있는데, 나중에 서버 url 이 바뀔 수 있기 때문에 지금 미리 따로 빼놓는 것이 좋을 거 같아요!

2022-07-11 04:51 UTC, hyejin-1010 commented on src/pages/SelectGroup.tsx
> +import { Suspense } from "react";
`Suspense` 는 코드에서 사용되지 않고 있는데, 넣어 두어야 하는 코드인가용 ?? 👀

2022-07-11 04:51 UTC, hyejin-1010 commented on src/pages/SelectGroup.tsx
> +import { Grid, } from "@mui/material";
개인적은 궁금증입니다! 💡
`{ Grid }` 가 아니라 `{ Grid, }` 와 같이 , 를 넣어놓는 게 어떤 의미가 있는 걸까요??

2022-07-11 04:51 UTC, hyejin-1010 commented on src/types/groupList.ts
> +type Group = {
여러 곳에서 사용할 수 있기 때문에 types 폴더에 type을 빼놓는 거니까, 아무래도 파일명이 `groupList.ts`보다는 두 개를 나눠서 `group.ts` `logo.ts`로 나누거나 ,, 으음 조금 더 공통적인 느낌이 나면 좋지 않을까하는 생각이 듭니다 🤔 이건 그냥 의견입니당 !!

2022-07-11 07:02 UTC, chochozabe commented on src/components/groupMap.tsx
> +class groupMap extends Component {
대신 답변 드리자면, react에는 컴포넌트를 정의하는 방법이 두가지입니다. 
class형과 function형인데요, 이 코드에서 사용한 class형 컴포넌트는 정의할 때 Component를 상속받습니다! 
component를 상속받으면 리액트에서 제공하는 기능을 모두 사용할 수 있게됩니다🙃

2022-07-11 07:03 UTC, hyejin-1010 commented on src/components/groupMap.tsx
> +class groupMap extends Component {
앗 제가 말을 모호하게썼네요! groupMap component 자체가 사용되고 있지 않은 것 같아서요!

2022-07-11 07:06 UTC, chochozabe commented on src/components/groupMap.tsx
> +class groupMap extends Component {
앗촤촤💃🏻 저는 Backstep 하겠습니다 ..

2022-07-11 07:54 UTC, kimsojung318 commented on src/apollo/client.tsx
> +    uri: "https://anniversary-archive.herokuapp.com/graphql",
수정했습니다!

2022-07-11 07:56 UTC, kimsojung318 commented on src/apollo/gql/selectGroupList.gql.tsx
> +query {
수정했습니다!

2022-07-11 07:56 UTC, kimsojung318 commented on src/components/layout/Header.tsx
> +import { Link } from 'react-router-dom';
잘못 들어간 것 같습니다! 삭제 했습니다!

2022-07-11 07:57 UTC, kimsojung318 commented on src/components/groupMap.tsx
> +class groupMap extends Component {
려경씨 말대로 컴포넌트를 따로 분리하려고 했다가 하지 않아서 삭제하는 것을 깜박했습니다ㅠㅠ 파일 삭제했습니다!

2022-07-11 08:00 UTC, kimsojung318 commented on src/components/selectGroupList.tsx
> +  const nameList: JSX.Element[] = data.groups.map((group:Group) =>
수정했습니다!

2022-07-11 08:01 UTC, kimsojung318 commented on src/pages/SelectGroup.tsx
> +import { Suspense } from "react";
삭제했습니다!

2022-07-11 08:02 UTC, kimsojung318 commented on src/pages/SelectGroup.tsx
> +import { Grid, } from "@mui/material";
기존 파일에서 Map으로 Box 생성까지 하다가 파일을 분리하고 미처 지우지 않은 것 같습니다. 지금 수정했습니다!

2022-07-11 08:06 UTC, kimsojung318 commented on src/types/groupList.ts
> +type Group = {
분리했습니다!

2022-07-11 08:07 UTC, chochozabe commented on src/components/selectGroupList.tsx
> +    const nameList: JSX.Element[] = data.groups.map((group:Groups, index:number) =>
그 컴포넌트 분리는 공용 컴포넌트라 아니라 코드 내에서 따로 함수로 작성하면 어떨까~ 하는 분리였습니다!! 
공용 컴포넌트라고 했어야했는데 제가 말을 헷갈리게 작성했네요😅

2022-07-11 09:08 UTC, kimsojung318 commented on src/components/selectGroupList.tsx
> +  const imgURL = "https://anniversary-archive.herokuapp.com/image/";
수정해서 커밋 올렸습니다!

2022-07-11 14:57 UTC, hyejin-1010 requested changes
수고하셨습니다! 코멘트 몇 개 달았는데 확인 부탁드립니다 ! 🙇‍♀️

2022-07-11 14:57 UTC, hyejin-1010 commented on src/components/selectGroupList.tsx
> +  const imgURL = `${process.env.REACT_APP_SERVER_URL}`+"/image/";
이 부분에 대해서는 개인적인 궁금증이 있어 여쭤봅니다! 보통 서버 url도 .env 파일로 빼나요??👀 저는 회사에서 주로 .env보다는 config에다가 넣는데, 다른 분들은 .env로 많이 빼시는 지 궁금해서 여쭤봅니다 !!

2022-07-11 14:57 UTC, hyejin-1010 commented on src/types/group.ts
> +import { Logo } from "./logo";
저만 이 부분 내려받고 실행하려고 하면 에러가 발생할까요..??
```
// logo.ts
type Logo_ = {
  filename: string;
  name: string;
  __typename: string;
  _id: string;
};
  
export type Logo = Logo_;
```
```
// group.ts
import { Logo } from "./logo";

type Group_ = {
  _id: string;
  name: string;
  logo: Logo;
};
  
export type Group = Group_;
```
이렇게 바꿔야만 에러가 발생하지 않던데,, 이 부분 확인 부탁드립니다!!

2022-07-11 15:12 UTC, kimsojung318 commented on src/types/group.ts
> +import { Logo } from "./logo";
일단 저는 두 방법 다 에러는 안 나네요.

2022-07-11 15:15 UTC, hyejin-1010 commented on src/types/group.ts
> +import { Logo } from "./logo";
앗 지금 해보니까 실행 시에는 문제가 없는데, 코드에서만 빨간줄이 보이네용,, 제 vscode 설정이 뭔가 잘 못 되어있나봐요,,, 죄송합니당 🙇‍♀️
<img width="782" alt="스크린샷 2022-07-12 오전 12 14 59" src="https://user-images.githubusercontent.com/31975198/178297673-62970b41-7455-4be3-9d4d-580aa841fd6b.png">

2022-07-11 15:52 UTC, chochozabe commented on src/components/selectGroupList.tsx
> +  const imgURL = `${process.env.REACT_APP_SERVER_URL}`+"/image/";
엇 저는 지금까지 늘 env 파일로 생성했는데 config로 빼기도 하는군요,,!

2022-07-12 02:55 UTC, hyejin-1010 commented on src/components/selectGroupList.tsx
> +  const imgURL = `${process.env.REACT_APP_SERVER_URL}`+"/image/";
해당 부분은 회사마다 다양하게 작업하는 것 같군요! 답변 감사합니다 🙇‍♀️

2022-07-12 02:55 UTC, hyejin-1010 approved these changes
LGFM👍🏼

2022-07-12 04:37 UTC, chochozabe approved these changes
수고하셨습니당☺️

2022-07-12 04:37 UTC, merged